"""add community

Revision ID: 1af76e015eee
Revises: 753a46794e77
Create Date: 2024-05-17 18:26:37.315530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af76e015eee'
down_revision = '753a46794e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('communityName', sa.String(length=15), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_communityName'), ['communityName'], unique=True)
        batch_op.create_index(batch_op.f('ix_community_timestamp'), ['timestamp'], unique=False)

    op.create_table('commembers',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'community_id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_community_id', 'community', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_community_id', type_='foreignkey')
        batch_op.drop_column('community_id')

    op.drop_table('commembers')
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_timestamp'))
        batch_op.drop_index(batch_op.f('ix_community_communityName'))
        batch_op.drop_index(batch_op.f('ix_community_category'))

    op.drop_table('community')
    # ### end Alembic commands ###
