"""profile table

Revision ID: 631479a61e44
Revises: 02c7a24cca2d
Create Date: 2024-05-14 14:30:53.862898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631479a61e44'
down_revision = '02c7a24cca2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('about_me', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
